{if $sorry}
<p>{_'LAYOUT.SERVICE_DOWN'}</p>
{else}
<ul class="feed twitter">
{foreach $items as $item}
	<li class="tweet">
		<abbr class="published" "title="{$item['date']|microformat:'datetime'}">
			<strong class="pub-day">{$item['date']|date:'%d'}</strong>
			<span class="pub-month">{$item['date']|date:'%m/%Y'}</span></abbr>
		{!$item['status']}
		<small><a href="{$item['link']}" title="{_'LAYOUT.PERMANENT_LINK'}">#</a></small>
	</li>
{/foreach}
</ul>
{/if}