{if $compact}
	<h2>{$person->name}</h2>
	<table>
		<tr>
			<th>{_'CONTACT.EMAIL'}</th>
			<td><a href="mailto:{!$person->email|email}">{!$person->email|email:TRUE}</a></td>
		</tr>
		<tr>
			<th>{_'CONTACT.PHONE'}</th>
			<td><a href="callto:{$person->phone}">{$person->phone|phone}</a></td>
		</tr>
		{if $lang == 'cs'}
		<tr>
			<th>{_'CONTACT.BANK'}</th>
			<td>{$person->bank}</td>
		</tr>
		{/if}
	</table>
{else}
	<div id="hcard-{$person->name}-{$person->surname}" class="vcard">
	<h2><span class="title">{$person->title}</span> <span class="fn">{$person->name} {$person->surname}</span></h2>
	
	<p>{!$bio}</p>
	
	{if count($person->publications)}
	<h3>{_'CONTACT.PUBLICATIONS'}</h3>
	<ul>
		{foreach $person->publications as $pub}
			<li><a href="{$pub->link}">{$pub->title}</a>{if $lang != $pub->lang} <sup>(<a href="{$pub->link|gtranslate:$pub->lang:$lang}">{=($lang == 'cs')? 'česky' : 'in English'}</a>)</sup>{/if}</li>
		{/foreach}
	</ul>
	{/if}
	
	<h3>{_'CONTACT.CONTACT'}</h3>
	<div class="businesscard">
	<img class="photo" src="{$basePath}/images/contacts/{$id}.png">
	<table>
		<tr>
			<th>{_'CONTACT.EMAIL'}</th>
			<td><a href="mailto:{!$person->email|email}" class="email">{!$person->email|email:TRUE}</a></td>
		</tr>
		<tr>
			<th>{_'CONTACT.PHONE'}</th>
			<td><a href="callto:{$person->phone}" class="tel">{$person->phone|phone}</a></td>
		</tr>
		<tr>
			<th>{_'CONTACT.SKYPE'}</th>
			<td><a href="skype:{$person->skype}?add">{$person->skype}</a>
			<img alt="Skype status" class="status" src="http://mystatus.skype.com/smallicon/{$person->skype}"></td>
		</tr>
		<tr>
			<th>{_'CONTACT.GOOGLE_ACCOUNT'}</th>
			<td><a href="xmpp:{!$person->google->mail|email}" class="url">{!$person->google->mail|email:TRUE}</a>
			<img alt="Google status" class="status" src="{!$person->google->badge}"></td>
		</tr>
	</table>
	
	<table>
		<tr>
			<th>{_'CONTACT.IC'}</th>
			<td><a href="http://wwwinfo.mfcr.cz/cgi-bin/ares/darv_rzp.cgi?ico={$person->ic}&jazyk={if $lang == 'cs'}cz{else}{$lang}{/if}&xml=1&rozsah=0">{$person->ic}</a></td>
		</tr>
		<tr>
			<th>{_'CONTACT.BANK'} {if $lang != 'cs'}(IBAN){/if}</th>
			<td>{if $lang == 'cs'}{$person->bank}{else}{$person->iban}{/if}</td>
		</tr>
		<tr>
			<th>{_'CONTACT.VAT'}</th>
			<td>{if $person->vat}{_'CONTACT.VAT_TRUE'}{else}{_'CONTACT.VAT_FALSE'}{/if}</td>
		</tr>
	</table>
	</div>
	
	<table class="listtable linkedin"><tr>
		<td>{!_'CONTACT.HIRE_ME'|inject:'LINKEDIN_USERNAME':$person->linkedin}</td>
		<th>
			<a href="http://www.linkedin.com/in/{$person->linkedin}">
			<img title="{_'CONTACT.LINKEDIN'}, {$person->name} {$person->surname}" alt="{_'CONTACT.LINKEDIN'}, {$person->name} {$person->surname}" src="{$basePath}/images/linkedin.png">
			</a>
		</th>
	</tr></table>
	</div>
{/if}