{block #content}

<div class="header">
<div class="wrapper">
	<h1>{$header}</h1>
	<p class="lead">{!_'ABOUT.SUBTITLE'}</p>
</div>
</div>

<hr>

<div class="clothesline">
<div class="section column mainleftcol">

<h2>{_'ABOUT.THANKS'}</h2>
<ul>
	<li><a href="http://www.nette.org/">Nette Framework</a></li>
	<li><a href="http://www.profitux.cz">profitux.cz</a></li>
	<li><a href="http://www.icondrawer.com">IconDrawer Flag Icons</a></li>
</ul>

<h2>{_'SITEMAP.HEADER'}</h2>
<ul class="sitemap">
{foreach $menu as $target => $name}
	<li><a href="{link $target}">{$name}</a></li>
{/foreach}
	<li><a href="{link Default:about}">{_'ABOUT.HEADER'}</a></li>
	<li><a href="{link Default:sitemap}">{_'SITEMAP.HEADER'}</a></li>
</ul>

</div>
<div class="section column siderightcol">

<p>{!_'ABOUT.LET_US_KNOW'|inject:CONTACT_LINK:$template->presenter->link('Default:contact')}</p>
<p>{!_'ABOUT.RIGHTS'}</p>

</div>
</div>
