{block #content}

<div class="header">
<div class="wrapper">
	<h1>{$header}</h1>
	<p class="lead">{!_'CONTACT.SUBTITLE'}</p>
</div>
</div>

<hr>

<div class="clothesline">
<div class="section column mainleftcol contacts">

	<div class="section" id="blocks">
	
	<div class="block firstblock">
	<div class="wrapper">
		{widget compactHonza}
		<p>
			<a class="more" href="#honza" rel="prettyPhoto">{_'LAYOUT.MORE'}</a>
		</p>
	</div>
	</div>
	
	<div class="block secondblock">
	<div class="wrapper">
		{widget compactMichal}
		<p>
			<a class="more" href="#michal" rel="prettyPhoto">{_'LAYOUT.MORE'}</a>
		</p>
	</div>
	</div>
	
	<div class="cleaner"><hr></div>
	</div>
	
<div class="tab" id="map">
	<h2>{_'CONTACT.WHERE'}</h2>
	<p>{_'CONTACT.MEETING'}</p>	
	<table id="map-legend">
		<tr><td rowspan="3">
			<div id="map-canvas"></div>
		</td><th>
			<h3><abbr class="geo" title="49.2;16.616667">{_'CONTACT.BRNO'}</abbr></h3>
			<p class="who"><em>Honza</em> <em>Michal</em></p>
		</th></tr>
		<tr><th>
			<h3><abbr class="geo" title="50.083333;14.416667">{_'CONTACT.PRAGUE'}</abbr></h3>
			<p class="who"><em>Honza</em></p>
		</th></tr>
		<tr><th>
			<h3><abbr class="geo" title="49.854167;18.542778">{_'CONTACT.KARVINA'}</abbr></h3>
			<p class="who"><em>Michal</em></p>
		</th></tr>
	</table>
</div>

<div class="contact tab" id="honza">
	{widget honza}
</div>

<div class="contact tab" id="michal">
	{widget michal}
</div>

</div>

<div class="section column siderightcol">

<h2>{_'CONTACT.ORGANIZING'}</h2>
{widget organized}

<h2>{_'CONTACT.ATTENDING'}</h2>
{widget conferences}

</div>
</div>

