<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html dir="ltr" lang="{$lang}">
<head profile="http://purl.org/uF/2008/03/">
	<meta http-equiv="content-type" content="text/html; charset=utf-8">
	<meta name="author" content="Honza Javorek, http://honza.javorek.net">
	<meta name="copyright" content="{$copyright} Honza Javorek + Michal Wiglasz">
	<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

		javorek.net

		{_'SLOGAN'}
		Copyright {$copyright} Honza Javorek + Michal Wiglasz, http://www.javorek.net/

		{_'LAYOUT.MOTD'}

	~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->

	{if isset($robots)}<meta name="robots" content="{$robots}">{/if}
	<meta name="verify-v1" content="O7RRNmseEFV6mKIjS/SLAufxKmxSwQ1scseuBhRMXgE=">
	<meta http-equiv="X-UA-Compatible" content="IE=8">

	<meta name="keywords" content="{$keywords}">
	<meta name="description" content="{$description}">

	<link rel="alternate" type="application/rss+xml" title="{_'LAYOUT.OUR_TWITTER'}" href="http://twitter.com/statuses/user_timeline/22777547.rss">

	<link rel="stylesheet" type="text/css" href="{$basePath}/css/framework.css" media="screen,projection,tv">
	<link rel="stylesheet" type="text/css" href="{$basePath}/css/main.css" media="screen,projection,tv">
	<!--[if lte IE 7]><link rel="stylesheet" type="text/css" href="{$basePath}/css/ie.css" media="screen,projection,tv"><![endif]-->
	<link rel="stylesheet" type="text/css" href="{$basePath}/css/print.css" media="print">

	<!-- jQuery, Google Maps API -->
	<script src="{$basePath}/js/jquery.min.js" type="text/javascript"></script>
	{if $presenter->getView() == 'contact'}<script src="http://maps.google.com/maps?file=api&amp;v=2&amp;sensor=false&amp;key=ABQIAAAAcI_qVFfqvblpC512MA5R6xQVFrKAcSLKPYd868CimRyWEEXTNhTGB9L2ASNtYAgBZNdkK1zXrMn_Bg" type="text/javascript"></script>{/if}

	<!-- Cufon -->
	<script src="{$basePath}/js/cufon-yui.js" type="text/javascript"></script>
	<script src="{$basePath}/js/Aller_400.font.js" type="text/javascript"></script>

	<!-- Effects -->
	<script src="{$basePath}/js/jquery.rounded.js" type="text/javascript"></script>
	<script src="{$basePath}/js/jquery.scrollTo.js" type="text/javascript"></script>
	<script src="{$basePath}/js/effects.js" type="text/javascript"></script>

	<link rel="shortcut icon" type="image/x-icon" href="{$basePath}/favicon.ico">
	<title>{$title}</title>

  <script type="text/javascript">

    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-1316071-8']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

  </script>
</head>
<body>
<div id="document">

<div class="header">
	<p id="logo"><strong><a href="{link Default:default}" title="{_'LAYOUT.HOME'}"><img src="{$basePath}/images/logo.png" alt="javorek.net: {_'SLOGAN'}"></a></strong></p>
	
	<div class="nav hidden"><p><a href="#languages">{=($lang == 'cs')? 'English version' : 'Česká verze'} &darr;</a>. {_'LAYOUT.JUMP_TO'} <a href="#menu" title="{_'LAYOUT.JUMP_NAV_TITLE'}">{_'LAYOUT.JUMP_NAV'} &darr;</a>.</p></div>
</div>

<hr>

<div class="article">
{foreach $flashes as $flash}<div class="flash {$flash->type}">{$flash->message}</div>{/foreach}
{include #content}
</div>

<hr>

<div class="nav" id="menu">
<h2 class="hidden">{_'LAYOUT.NAVIGATION'}</h2>
<ul>
	{foreach $menu as $target => $name}
	<li{ifCurrent $target} class="active"{/if}><a href="{link $target}">{$name}</a></li>
	{/foreach}
</ul>
</div>

<hr>

<div class="nav" id="languages">
<h2 class="hidden">{_'LAYOUT.LANGUAGES'}</h2>
<ul>
	<li class="lang-cs"><a href="{$presenter->link($presenter->backlink(), array('lang' => 'cs'))}">Česky<span></span></a></li>
	<li class="lang-en"><a href="{$presenter->link($presenter->backlink(), array('lang' => 'en'))}">English<span></span></a></li>
</ul>
</div>

<hr>

<div class="aside" id="follow">
<h2 class="hidden">{_'LAYOUT.FOLLOW_US'}</h2>
<ul>
	<li><a href="http://twitter.com/statuses/user_timeline/22777547.rss" class="rss">Javorek &mdash; Twitter RSS<span></span></a></li>
	<li><a href="http://www.facebook.com/javoreknet" class="facebook">Javorek &mdash; Facebook<span></span></a></li>
	<li><a href="https://twitter.com/javoreknet" class="twitter">Javorek &mdash; Twitter<span></span></a></li>
	<li><a href="http://www.linkedin.com/companies/javorek" class="linkedin">Javorek &mdash; LinkedIn<span></span></a></li>
</ul>
</div>

<hr>

<div class="footer">
	<p id="copyright"><strong>Honza Javorek + Michal Wiglasz = <a href="http://www.javorek.net/" title="Javorek">{_'SLOGAN'}</a></strong> <small>{$copyright}</small><br>
	<span class="unimportant"><a href="{link Default:about}">{_'ABOUT.HEADER'} &amp; {_'SITEMAP.HEADER'}</a></span></p>
	
	<div class="nav hidden"><p>{_'LAYOUT.JUMP_TO'} <a href="#document" title="{_'LAYOUT.JUMP_UP_TITLE'}">{_'LAYOUT.JUMP_UP'} &uarr;</a>.</p></div>
</div>

</div>
</body>
</html>
